# ==========================================
# Configuración Didáctica Mínima de Snort
# ==========================================

# Red local (subredes de Docker y localhost) y red externa
ipvar HOME_NET [172.16.0.0/12,192.168.0.0/16,10.0.0.0/8,127.0.0.1/32]
ipvar EXTERNAL_NET any

# Ruta de las reglas
var RULE_PATH /etc/snort/rules

# Desactivar decodificadores innecesarios para evitar falsas alarmas locales
config checksum_mode: none

# Configuración de salida de alertas a consola en formato rápido
output alert_fast: stdout

# Cargar únicamente nuestras reglas educativas locales
include $RULE_PATH/local.rules
