[Definition]
# Detecta intentos fallidos de inicio de sesión que retornen códigos 401 (Unauthorized) o 403 (Forbidden)
failregex = ^<HOST> - - \[.*\] "POST /api/auth/login HTTP/.*" (?:401|403)\s
ignoreregex =
