[Definition]
# Busca peticiones GET que intenten acceder a extensiones y carpetas sensibles comunes (WP, PHP, env) que devuelvan 404
failregex = ^<HOST> - - \[.*\] "GET .*(?:\.php|\.asp|\.aspx|\.exe|\.pl|\.cgi|\.env|\.git|wp-admin|wp-login|setup\.sh|phpmyadmin) HTTP/.*" 404\s
ignoreregex =
